### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  id: ServiceDiscoveryElement
  children:
  - System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.#ctor
  - System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.AnnouncementEndpoints
  - System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.BehaviorType
  - System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.CreateBehavior
  - System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.Properties
  langs:
  - csharp
  name: ServiceDiscoveryElement
  nameWithType: ServiceDiscoveryElement
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  type: Class
  summary: "Representa um elemento de configuração que controla a capacidade de descoberta de um serviço."
  remarks: "Quando esse elemento é aplicado à configuração de comportamento de um serviço, todos os pontos de extremidade expostos podem ser descobertos pelo serviço. O exemplo a seguir mostra como marcar um serviço como detectável. Você pode usar <xref:System.ServiceModel.Discovery.Configuration.EndpointDiscoveryElement>para controlar a capacidade de descoberta de um ponto de extremidade específico.</xref:System.ServiceModel.Discovery.Configuration.EndpointDiscoveryElement>      ```   <configuration>       <system.serviceModel>         <services>           <service name=&quot;Microsoft.Samples.Discovery.CalculatorService&quot;                    behaviorConfiguration=&quot;calculatorServiceBehavior&quot;>             <endpoint address=&quot;&quot;                       binding=&quot;wsHttpBinding&quot;                       contract=&quot;Microsoft.Samples.Discovery.ICalculatorService&quot;/>           </service>         </services>         <behaviors>           <serviceBehaviors>             <behavior name=&quot;calculatorServiceBehavior&quot;>               <serviceDiscovery />             </behavior>           </serviceBehaviors>           </system.serviceModel>   </configuration>      ```"
  syntax:
    content: 'public sealed class ServiceDiscoveryElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  langs:
  - csharp
  name: ServiceDiscoveryElement()
  nameWithType: ServiceDiscoveryElement.ServiceDiscoveryElement()
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.ServiceDiscoveryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Cria uma nova instância do <xref href=&quot;System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement&quot;> </xref> classe."
  syntax:
    content: public ServiceDiscoveryElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.AnnouncementEndpoints
  id: AnnouncementEndpoints
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  langs:
  - csharp
  name: AnnouncementEndpoints
  nameWithType: ServiceDiscoveryElement.AnnouncementEndpoints
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.AnnouncementEndpoints
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Obtém uma coleção de pontos de extremidade de anúncio."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.AnnouncementChannelEndpointElementCollection AnnouncementEndpoints { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.AnnouncementChannelEndpointElementCollection
      description: "Um <xref href=&quot;System.ServiceModel.Configuration.ChannelEndpointElementCollection&quot;> </xref> que contém pontos de extremidade de anúncio."
  overload: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.AnnouncementEndpoints*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: ServiceDiscoveryElement.BehaviorType
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Obtém o tipo de comportamento."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "O tipo do comportamento."
  overload: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: ServiceDiscoveryElement.CreateBehavior()
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "A ser adicionado."
  overload: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceDiscoveryElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A ser adicionado."
  overload: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: ServiceDiscoveryElement()
  nameWithType: ServiceDiscoveryElement.ServiceDiscoveryElement()
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.ServiceDiscoveryElement()
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.AnnouncementEndpoints
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: AnnouncementEndpoints
  nameWithType: ServiceDiscoveryElement.AnnouncementEndpoints
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.AnnouncementEndpoints
- uid: System.ServiceModel.Discovery.Configuration.AnnouncementChannelEndpointElementCollection
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: AnnouncementChannelEndpointElementCollection
  nameWithType: AnnouncementChannelEndpointElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.AnnouncementChannelEndpointElementCollection
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.BehaviorType
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: BehaviorType
  nameWithType: ServiceDiscoveryElement.BehaviorType
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.CreateBehavior
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: ServiceDiscoveryElement.CreateBehavior()
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: Properties
  nameWithType: ServiceDiscoveryElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: ServiceDiscoveryElement
  nameWithType: ServiceDiscoveryElement.ServiceDiscoveryElement
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.AnnouncementEndpoints*
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: AnnouncementEndpoints
  nameWithType: ServiceDiscoveryElement.AnnouncementEndpoints
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.BehaviorType*
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: BehaviorType
  nameWithType: ServiceDiscoveryElement.BehaviorType
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.CreateBehavior*
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: CreateBehavior
  nameWithType: ServiceDiscoveryElement.CreateBehavior
- uid: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement
  isExternal: false
  name: Properties
  nameWithType: ServiceDiscoveryElement.Properties
